### ISSUE TITLE
Current `git init` logic is broken

### ISSUE THREAD

**Issue by shaftoe** [probot/create-probot-app#356]
See: https://github.com/probot/create-probot-app/pull/355/checks?check_run_id=1833790485#step:7:37

```
Initializing Git repository in folder '/tmp/tmp.pDwQ5x5x0m/basic-js'
Cleaning up /tmp/tmp.pDwQ5x5x0m/basic-js/.git folder
Error: Author identity unknown
```

Basically it assumes Git has been configured which might not always be the case (e.g. in the test environment)

**Comment by MaximDevoir** [comment]
I failed to find the error in the logs. Could you send a link to the line where it is at?

The tests should still resume, even with an unconfigured Git installation, as is intended.

The initialization should be working as intended. If Git is installed but not configured, then https://github.com/probot/create-probot-app/blob/master/src/helpers/init-git.ts should do as follows:

1. pre-requisite check (is Git installed, are we in a Git repo already?)
1. Run `git init` command via `simplegit`. If Git has been configured, it will move onto the next step. If git has not been configured, the `git init` command will be caught.

https://github.com/probot/create-probot-app/blob/25b3196783bdaef48d720db64cd8ff38b9b22a35/src/helpers/init-git.ts#L59-L68

Since git has not been initialized, The step should silently fail and move onto the next part of CPA initialization.

**Comment by shaftoe** [comment]
Sorry, I guess I pasted the wrong link, this should do: https://github.com/probot/create-probot-app/runs/1833790507?check_suite_focus=true#step:7:36

The full message for the records:

```
Initializing Git repository in folder '/tmp/tmp.wQ4KXnKrXM/basic-js'
Cleaning up /tmp/tmp.wQ4KXnKrXM/basic-js/.git folder
Error: Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az184-935.ytpcfoii4iourexjgkmagftyea.cx.internal.cloudapp.net>) not allowed
```

My understanding is that all you say is true only under the condition that Git has been previously configured in the working environment where CPA is run. I've noticed the above error simply replacing `./tmp-tests` with `mkdir -d` output in the test script.

**Comment by MaximDevoir** [comment]
Seems like an issue. A method for silently moving onto the next step seems like a solution for the edge case.
