### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by gr2m** [probot/create-probot-app#91]
https://travis-ci.org/probot/create-probot-app/builds/610048199?utm_source=github_status&utm_medium=notification

**Comment by MaximDevoir** [comment]
I'm unable to reproduce this locally on Ubuntu 18.04 (uh oh - gonna have to pull out ol' Docker), but this appears to be caused by the `semantic-release` dependency installing npm. Once `semantic-release` was removed and the lock-file was updated, the error went away.

I'l take a closer look at  this so we can keep `semantic-release` as a devDependency.

**Comment by gr2m** [comment]
Okay thanks! I wonder what the problem with `semantic-release` could be, I use it a lot in other actions. Worst case we can just run `npx semantic-release` without installing it as devDependency, or uninstall it before installing the dependencies for the tests
